import type { Metadata } from "next";
import { Anuphan, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalFooter from "@/app/artist/[id]/components/ConditionalFooter"; // 👈 เปลี่ยนมา import ตัวนี้แทน

const anuphan = Anuphan({
  subsets: ["thai", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-anuphan",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="th"
      className={`${anuphan.variable} font-sans h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        {/* ครอบ children ด้วย main พร้อม flex-grow เพื่อดัน Footer ลงไปล่างสุด */}
        <main className="flex-grow">
          {children}
        </main>
        
        {/* วาง ConditionalFooter ไว้ล่างสุดตรงนี้ */}
        <ConditionalFooter />
      </body>
    </html>
  );
}