/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/artists/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * UpdateMyArtistProfile
     * @description Update the authenticated artist's description or public profile image
     */
    put: operations["update-my-artist-profile"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/artists/{artist_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * GetArtistProfile
     * @description Get a public artist profile with artwork-derived details and paginated reviews
     */
    get: operations["get-artist-profile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/artists/{artist_id}/artworks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * GetArtistArtworks
     * @description Get every artwork created by an artist, newest first
     */
    get: operations["get-artist-artworks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/artworks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * CreateArtwork
     * @description Create portfolio artwork owned by the authenticated artist
     */
    post: operations["create-artwork"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/artworks/{artwork_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * UpdateArtwork
     * @description Update portfolio artwork owned by the authenticated artist
     */
    put: operations["update-artwork"];
    post?: never;
    /**
     * DeleteArtwork
     * @description Delete portfolio artwork owned by the authenticated artist
     */
    delete: operations["delete-artwork"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description Log in with email and password
     */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Log out and terminate the current session
     */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh
     * @description Exchange a refresh token (cookie) for a new access token
     */
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register
     * @description Register a new account
     */
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * ViewOrders
     * @description List the authenticated customer's or artist's orders, filtered by status, sorted by deadline/price/updated_at, and paginated by limit/offset. deliverable_preview_url is the artist's most recently submitted deliverable preview, presigned and time-limited, regardless of order status; null if none has been submitted yet.
     */
    get: operations["view-orders"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * GetAccount
     * @description Get the authenticated user's account information
     */
    get: operations["get-account"];
    /**
     * UpdateAccount
     * @description Update the authenticated user's username and optionally change their password
     */
    put: operations["update-account"];
    post?: never;
    /**
     * DeleteAccount
     * @description Delete the authenticated user's account when they have no active orders
     */
    delete: operations["delete-account"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me/bank-account": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * GetBankAccount
     * @description Get the authenticated user's bank account
     */
    get: operations["get-bank-account"];
    /**
     * UpdateBankAccount
     * @description Update the authenticated user's bank account
     */
    put: operations["update-bank-account"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AccountView: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example /api/v1/schemas/AccountView.json
       */
      readonly $schema?: string;
      email: string;
      id: string;
      role: string;
      username: string;
    };
    ArtistArtworkView: {
      artwork_id: string;
      artwork_samples: components["schemas"]["ArtworkSampleView"][] | null;
      category: string;
      description: string;
      /** Format: int64 */
      minimum_deadline_days: number;
      name: string;
      /** Format: int64 */
      price_satang: number;
      styles: string[] | null;
    };
    ArtistProfileView: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example /api/v1/schemas/ArtistProfileView.json
       */
      readonly $schema?: string;
      artist_id: string;
      artist_name: string;
      categories: components["schemas"]["ArtistReferenceView"][] | null;
      description: string | null;
      /** Format: int64 */
      max_price_satang: number | null;
      /** Format: int64 */
      min_price_satang: number | null;
      profile_url: string | null;
      /** Format: double */
      review_score: number | null;
      reviews: components["schemas"]["ArtistReviewView"][] | null;
      styles: components["schemas"]["ArtistReferenceView"][] | null;
      /** Format: int64 */
      total: number;
    };
    ArtistReferenceView: {
      id: string;
      label: string;
    };
    ArtistReviewView: {
      order: string;
      /** Format: int64 */
      rating: number;
      username: string;
    };
    ArtworkSampleView: {
      /** Format: uri */
      image_url: string;
    };
    ArtworkView: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example /api/v1/schemas/ArtworkView.json
       */
      readonly $schema?: string;
      artist_id: string;
      artwork_samples: components["schemas"]["ArtworkSampleView"][] | null;
      category: string;
      /** Format: date-time */
      created_at: string;
      description: string;
      id: string;
      /** Format: int64 */
      minimum_deadline_days: number;
      name: string;
      /** Format: int64 */
      price_satang: number;
      styles: string[] | null;
      /** Format: date-time */
      updated_at: string;
    };
    AuthResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example /api/v1/schemas/AuthResultBody.json
       */
      readonly $schema?: string;
      access_token: string;
    };
    BankAccountView: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example /api/v1/schemas/BankAccountView.json
       */
      readonly $schema?: string;
      account_holder_name: string;
      account_last4: string;
      bank_name: string;
    };
    ErrorDetail: {
      /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
      location?: string;
      /** @description Error message text */
      message?: string;
      /** @description The value at the given location */
      value?: unknown;
    };
    ErrorModel: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example /api/v1/schemas/ErrorModel.json
       */
      readonly $schema?: string;
      /**
       * @description A human-readable explanation specific to this occurrence of the problem.
       * @example Property foo is required but is missing.
       */
      detail?: string;
      /** @description Optional list of individual error details */
      errors?: components["schemas"]["ErrorDetail"][] | null;
      /**
       * Format: uri
       * @description A URI reference that identifies the specific occurrence of the problem.
       * @example https://example.com/error-log/abc123
       */
      instance?: string;
      /**
       * Format: int64
       * @description HTTP status code
       * @example 400
       */
      status?: number;
      /**
       * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
       * @example Bad Request
       */
      title?: string;
      /**
       * Format: uri
       * @description A URI reference to human-readable documentation for the error.
       * @default about:blank
       * @example https://example.com/errors/example
       */
      type: string;
    };
    GetArtistArtworksOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example /api/v1/schemas/GetArtistArtworksOutputBody.json
       */
      readonly $schema?: string;
      artworks: components["schemas"]["ArtistArtworkView"][] | null;
    };
    LoginInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example /api/v1/schemas/LoginInputBody.json
       */
      readonly $schema?: string;
      /** Format: email */
      email: string;
      password: string;
    };
    OrderSummaryView: {
      artist_id: string;
      /** Format: date-time */
      completed_at?: string;
      /** Format: date-time */
      created_at: string;
      customer_id: string;
      /** Format: date-time */
      deadline_at?: string;
      /** @description Presigned URL of the most recently submitted deliverable's preview image, regardless of order status; null if none has been submitted yet. */
      deliverable_preview_url: string | null;
      id: string;
      name: string;
      /** Format: int64 */
      price_satang: number;
      status: string;
      /** Format: date-time */
      updated_at: string;
    };
    RegisterArtistBody: {
      description?: string;
    };
    RegisterBankAccountBody: {
      account_holder_name: string;
      account_number: string;
      bank_name: string;
    };
    RegisterInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example /api/v1/schemas/RegisterInputBody.json
       */
      readonly $schema?: string;
      artist?: components["schemas"]["RegisterArtistBody"];
      bank_account: components["schemas"]["RegisterBankAccountBody"];
      /** Format: email */
      email: string;
      password: string;
      /** @enum {string} */
      role: "customer" | "artist";
      username: string;
    };
    UpdateAccountInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example /api/v1/schemas/UpdateAccountInputBody.json
       */
      readonly $schema?: string;
      new_password?: string;
      old_password?: string;
      username: string;
    };
    UpdateBankAccountInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example /api/v1/schemas/UpdateBankAccountInputBody.json
       */
      readonly $schema?: string;
      account_holder_name: string;
      account_number: string;
      bank_name: string;
    };
    ViewOrdersOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example /api/v1/schemas/ViewOrdersOutputBody.json
       */
      readonly $schema?: string;
      orders: components["schemas"]["OrderSummaryView"][] | null;
      /** Format: int64 */
      total: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "update-my-artist-profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          description?: string;
          /** Format: binary */
          profile_image?: string;
          remove_profile_image?: boolean;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArtistProfileView"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "get-artist-profile": {
    parameters: {
      query?: {
        /** @description Maximum number of reviews to return. */
        limit?: number;
        /** @description Number of reviews to skip. */
        offset?: number;
      };
      header?: never;
      path: {
        artist_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArtistProfileView"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "get-artist-artworks": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        artist_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetArtistArtworksOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "create-artwork": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          artwork_samples?: string[];
          category: string;
          description: string;
          /** Format: int64 */
          minimum_deadline_days: number;
          name: string;
          /** Format: int64 */
          price_satang: number;
          styles: string[] | null;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArtworkView"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "update-artwork": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        artwork_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          category: string;
          deleted_sample_urls?: string[] | null;
          description: string;
          /** Format: int64 */
          minimum_deadline_days: number;
          name: string;
          /** Format: int64 */
          price_satang: number;
          styles: string[] | null;
          uploaded_samples?: string[];
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArtworkView"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "delete-artwork": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        artwork_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResultBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        refresh_token?: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResultBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterInputBody"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "view-orders": {
    parameters: {
      query?: {
        /** @description Filter by one or more order statuses. Repeated values are OR'd. Omit for every status. */
        status?:
          | ("PENDING" | "NOT_PAID" | "IN_PROCESS" | "SUCCESS" | "CANCEL")[]
          | null;
        /** @description Field to sort by. */
        sort?: "deadline" | "price" | "updated_at";
        /** @description Sort direction. */
        order?: "asc" | "desc";
        /** @description Maximum number of orders to return. */
        limit?: number;
        /** @description Number of matching orders to skip before the first returned row. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ViewOrdersOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "get-account": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountView"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "update-account": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAccountInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountView"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "delete-account": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "get-bank-account": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BankAccountView"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "update-bank-account": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateBankAccountInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BankAccountView"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
}
